### ISSUE TITLE
Labels are hidden by the mouse and ignore styling

### ISSUE THREAD

**Issue by ewirtz65** [vasturiano/3d-force-graph#347]
When displaying the label it appears under the mouse making it difficult to read.  Is it possible to change the styling and position on this?

In general the text seems unaffected by the class of the container.

**Comment by vasturiano** [comment]
@ewirtz65 thanks for reaching out.

You can manipulate the tooltip position by overriding the transform style attribute on it.
F.e.:
```css
.scene-tooltip {
  transform: translate(-50%, -25px) !important;
}
```
