### ISSUE TITLE
Node label color

### ISSUE THREAD

**Issue by wangpeio** [vasturiano/3d-force-graph#410]
How to change the color of node labels？

**Comment by RaulPROP** [comment]
You can change it using css.

```css
.scene-tooltip {
    color: green;
    background: yellow;
}
```

[Example](https://codepen.io/raulprop/pen/NWrQZBX?editors=0111).
