### ISSUE TITLE
How to change font family in text nodes?

### ISSUE THREAD

**Issue by haendzel** [vasturiano/3d-force-graph#572]
The question is in the title.

**Comment by mneunomne** [comment]
For example:

```js
.nodeThreeObject(node => {
    const sprite = new SpriteText(node.id);
    sprite.fontFace = "roboto-mono";
    return sprite;
  });
```

And on your css configurations:
```css
 @font-face {
      font-family: 'roboto-mono';
      src: url('./fonts/SpaceMono-Regular.ttf') format('truetype');
    }
```
